package com.coyotai.education.auth;

/**
 * Every permission code the code base checks. The database holds the same codes (Flyway V7);
 * a test verifies that every {@code @PreAuthorize} in the API refers to one of these, so a
 * typo can never silently lock an endpoint.
 */
public enum PermissionCode {
    DASHBOARD_VIEW,

    USER_VIEW, USER_MANAGE,
    ROLE_VIEW, ROLE_MANAGE,
    SETTINGS_VIEW, AUDIT_VIEW,
    PARENT_VIEW, PARENT_MANAGE,

    STUDENT_VIEW, ASSIGNED_STUDENT_VIEW, STUDENT_CREATE, STUDENT_UPDATE,
    MENTOR_VIEW, MENTOR_MANAGE,
    FACULTY_VIEW, FACULTY_MANAGE,

    COURSE_VIEW, COURSE_CREATE, COURSE_UPDATE,
    SUBJECT_VIEW, SUBJECT_CREATE, SUBJECT_UPDATE,
    ACADEMIC_YEAR_VIEW, ACADEMIC_YEAR_MANAGE,
    BATCH_VIEW, BATCH_CREATE, BATCH_UPDATE, MY_BATCH_VIEW,
    MASTER_DATA_MANAGE,

    SCHEDULE_VIEW, SCHEDULE_CREATE, SCHEDULE_UPDATE, MY_SCHEDULE_VIEW,
    ATTENDANCE_VIEW, ATTENDANCE_CREATE, ATTENDANCE_UPDATE,
    DISCIPLINE_VIEW, DISCIPLINE_CREATE, DISCIPLINE_UPDATE,
    FINE_VIEW, FINE_CREATE, FINE_UPDATE,
    TEST_VIEW, TEST_CREATE, TEST_MARKS_ENTRY, TEST_PUBLISH,
    EXAM_VIEW, EXAM_CREATE, EXAM_MARKS_ENTRY, EXAM_PUBLISH,
    PERFORMANCE_VIEW,
    PROGRESS_CARD_VIEW, PROGRESS_CARD_CREATE, PROGRESS_CARD_PUBLISH,
    SYLLABUS_VIEW, SYLLABUS_MANAGE, SYLLABUS_UPDATE,
    PARENT_MEETING_VIEW, PARENT_MEETING_CREATE,
    CLASS_REGISTER_VIEW, CLASS_REGISTER_CREATE,
    FACULTY_ENTRY_EXIT_VIEW, FACULTY_ENTRY_EXIT_CREATE,

    FEE_VIEW, FEE_MANAGE, PAYMENT_CREATE,

    NOTIFICATION_VIEW, NOTIFICATION_MANAGE,

    REPORT_VIEW,

    MY_PROFILE_VIEW, MY_ATTENDANCE_VIEW, MY_TEST_RESULTS_VIEW, MY_EXAM_RESULTS_VIEW,
    MY_PERFORMANCE_VIEW, MY_PROGRESS_CARD_VIEW, MY_DISCIPLINE_VIEW, MY_FINE_VIEW,
    MY_FEE_VIEW, MY_SYLLABUS_VIEW, MY_NOTIFICATION_VIEW
}
